services:
  app-full:
    build: ./full
    container_name: adminer-ocl-app-full
    volumes:
      - ./adminer-servers.php/:/var/www/html/adminer-servers.php
    ports:
      - 80:80
  app-mongo:
    build: ./mongo
    container_name: adminer-ocl-app-mongo
    volumes:
      - ./adminer-servers-mongo.php/:/var/www/html/adminer-servers.php
    ports:
      - 81:80
  app-mysql:
    build: ./mysql
    container_name: adminer-ocl-app-mysql
    volumes:
      - ./adminer-servers-mysql.php/:/var/www/html/adminer-servers.php
    ports:
      - 82:80
  app-postgre:
    build: ./postgre
    container_name: adminer-ocl-app-postgre
    volumes:
      - ./adminer-servers-postgre.php/:/var/www/html/adminer-servers.php
    ports:
      - 83:80
  db-mysql:
    image: mysql:8
    container_name: adminer-ocl-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
  db-mongo:
    image: mongo
    container_name: adminer-ocl-db-mongo
    environment:
      MONGO_INITDB_DATABASE: local
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local
  db-postgre:
    image: postgres:16-alpine
    container_name: adminer-ocl-db-postgre
    environment:
      POSTGRES_DB: local
      POSTGRES_PASSWORD: local
      POSTGRES_USER: local
  node:
    build: ./node
    container_name: adminer-ocl-node
    volumes:
      - ./:/app
networks:
  adminer-ocl:
    name: adminer-ocl