FROM alpine:3.14

LABEL maintainer="Ivan Iashin <newparadigma1@gmail.com>"

ENV ADMINER_VERSION=4.8.1
ENV MEMORY=256M
ENV UPLOAD=2048M
ENV WORKERS=4
ENV PHP_CLI_SERVER_WORKERS=${WORKERS}
ENV WORKDIR=/var/www/html

ENV ADMINER_PHP=https://github.com/vrana/adminer/releases/download/v$ADMINER_VERSION/adminer-$ADMINER_VERSION.php
ENV PLUGIN_PHP=https://raw.githubusercontent.com/vrana/adminer/master/plugins/plugin.php
ENV ONE_CLICK_LOGIN=https://raw.githubusercontent.com/newparadigma/one-click-login/master/oneclick-login.php
ENV ADMINER_WITH_PLUGINS=https://raw.githubusercontent.com/newparadigma/adminer-one-click-login/main/adminer-with-plugins.php

RUN echo '@community http://nl.alpinelinux.org/alpine/v3.14/community' >> /etc/apk/repositories && \
    apk update && \
    apk upgrade && \
    apk add \
        wget \
        ca-certificates \
        php8@community \
        php8-session@community \
        php8-pecl-mongodb@community \
        tini && \
    mkdir -p $WORKDIR/plugins && \
    wget $ADMINER_PHP -O $WORKDIR/adminer.php && \
    wget $PLUGIN_PHP -O $WORKDIR/plugins/plugin.php && \
    wget $ONE_CLICK_LOGIN -O $WORKDIR/plugins/oneclick-login.php && \
    wget $ADMINER_WITH_PLUGINS -O $WORKDIR/index.php && \
    ln -s /usr/bin/php8 /usr/bin/php && \
    apk del wget ca-certificates && \
    rm -rf /var/cache/apk/*

WORKDIR $WORKDIR
EXPOSE 80

ENTRYPOINT ["/sbin/tini", "--"]

CMD /usr/bin/php \
    -d memory_limit=$MEMORY \
    -d upload_max_filesize=$UPLOAD \
    -d post_max_size=$UPLOAD \
    -S 0.0.0.0:80
