name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push newparadigma/adminer-one-click-login:full
      uses: docker/build-push-action@v6
      with:
        context: ./full
        platforms: linux/amd64,linux/i386,linux/arm/v6,linux/arm/v7,linux/arm/v8
        push: true
        tags: newparadigma/adminer-one-click-login:full

    - name: Build and push newparadigma/adminer-one-click-login:latest
      uses: docker/build-push-action@v6
      with:
        context: ./full
        platforms: linux/amd64,linux/i386,linux/arm/v6,linux/arm/v7,linux/arm/v8
        push: true
        tags: newparadigma/adminer-one-click-login:latest

    - name: Build and push newparadigma/adminer-one-click-login:mysql
      uses: docker/build-push-action@v6
      with:
        context: ./mysql
        platforms: linux/amd64,linux/i386,linux/arm/v6,linux/arm/v7,linux/arm/v8
        push: true
        tags: newparadigma/adminer-one-click-login:mysql

    - name: Build and push newparadigma/adminer-one-click-login:mongo
      uses: docker/build-push-action@v6
      with:
        context: ./mongo
        platforms: linux/amd64,linux/i386,linux/arm/v6,linux/arm/v7,linux/arm/v8
        push: true
        tags: newparadigma/adminer-one-click-login:mongo

    - name: Build and push newparadigma/adminer-one-click-login:postgre
      uses: docker/build-push-action@v6
      with:
        context: ./postgre
        platforms: linux/amd64,linux/i386,linux/arm/v6,linux/arm/v7,linux/arm/v8
        push: true
        tags: newparadigma/adminer-one-click-login:postgre