name: Build and Push Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      run: make docker-build-and-push

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: |
    #       your-dockerhub-username/your-repo-name:latest
    #       your-dockerhub-username/your-repo-name:${{ github.sha }}

    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     platforms: linux/amd64,linux/i386,linux/arm/v6,linux/arm/v7,linux/arm/v8
    #     push: true
    #     tags: user/app:latest